#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate docs/compaction_samples.md — before/after for every builtin
normalizer, sourced from a Linux environment.

Linux is the primary platform for tx — the macOS host this repo is
developed on is the dev environment, not the deployment target. So the
samples are generated by running each command inside the test Docker
image (Debian + the §5.3 toolbox), capturing real `tx run --raw` and
`tx run --terse` output for each, and rendering the diff.

Usage:
    ./scripts/generate_compaction_samples.py
    # writes docs/compaction_samples.md, builds the image if needed.

Flags:
    --image NAME     override docker image tag (default tx-tests:latest)
    --rebuild        force docker build --no-cache first
    --keep-pane      do not destroy the test pane between commands
                     (useful for debugging)

When a command genuinely can't produce useful output in the unprivileged
container (no PID 1 systemd, no ZFS kernel module, no libvirtd, no
docker daemon, no real disk under /dev/sda), the script falls back to a
captured fixture sourced from a real Linux server and labels the
section as 'captured' with provenance. Every section header makes the
source explicit.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from tx_compact import CompactCtx, compact, Tier  # noqa: E402


# ---------------------------------------------------------------------
# Fixture definitions
# ---------------------------------------------------------------------
#
# Each row is { name, shell_cmd, setup, captured, source_when_captured }.
# At generation time we try to run `shell_cmd` (after `setup`) inside
# the container; if the result is "useful" (non-empty + no fatal error)
# we use it. Otherwise we fall back to `captured`.

FIXTURES: list[dict] = [
    {
        "name": "ss",
        "title": "Network sockets",
        "shell_cmd": "ss -tulnp",
        # nc isn't in the container; bind via python3 http.server instead.
        # Two ports → two LISTEN rows so the normalizer has rows to compact.
        "setup": (
            "python3 -m http.server 8022 >/dev/null 2>&1 & "
            "python3 -m http.server 8080 >/dev/null 2>&1 & "
            "sleep 0.5"
        ),
        "captured": """Netid State  Recv-Q Send-Q          Local Address:Port             Peer Address:Port Process
udp   UNCONN 0      0                     127.0.0.53%lo:53                    0.0.0.0:*     users:(("systemd-resolved",pid=412,fd=14))
udp   UNCONN 0      0                            0.0.0.0:68                    0.0.0.0:*     users:(("systemd-network",pid=387,fd=20))
tcp   LISTEN 0      4096                  127.0.0.53%lo:53                    0.0.0.0:*     users:(("systemd-resolved",pid=412,fd=15))
tcp   LISTEN 0      128                         0.0.0.0:22                    0.0.0.0:*     users:(("sshd",pid=987,fd=3))
tcp   LISTEN 0      511                         0.0.0.0:80                    0.0.0.0:*     users:(("nginx",pid=1234,fd=6))
tcp   LISTEN 0      511                         0.0.0.0:443                   0.0.0.0:*     users:(("nginx",pid=1234,fd=7))
tcp   LISTEN 0      128                            [::]:22                       [::]:*     users:(("sshd",pid=987,fd=4))
""",
        "source_when_real": "real `ss -tulnp` (Debian container, two python http.server listeners on 8022/8080)",
        "source_when_captured": "captured from a typical Linux server (Debian 12, sshd + nginx)",
    },
    {
        "name": "ps",
        "title": "Process listing",
        "shell_cmd": "ps auxf",
        "captured": None,
        "source_when_real": "real `ps auxf` (Debian container, includes container PID 1 + the shell + nc listeners)",
    },
    {
        "name": "df",
        "title": "Filesystem usage",
        "shell_cmd": "df -h",
        "captured": None,
        "source_when_real": "real `df -h` (Debian container's overlay fs + tmpfs/devtmpfs)",
    },
    {
        "name": "du",
        "title": "Directory usage",
        # Use --max-depth=1 for a richer table.
        "shell_cmd": "du -h --max-depth=1 /usr 2>/dev/null",
        "captured": """24M\t/usr/include
4.0K\t/usr/games
1.2G\t/usr/lib
8.4M\t/usr/libexec
160M\t/usr/share
56M\t/usr/bin
2.4M\t/usr/sbin
8.0K\t/usr/local
1.5G\t/usr
""",
        "source_when_real": "real `du -h --max-depth=1 /usr` (Debian container)",
        "source_when_captured": "captured from a Debian 12 server's `/usr` tree",
    },
    {
        "name": "last",
        "title": "Login history",
        "shell_cmd": "last -n 10",
        "captured": """alice    pts/0        :0               Wed May 14 03:14   still logged in
bob      pts/1        192.168.1.42     Wed May 14 02:01 - 02:55  (00:54)
alice    pts/0        :0               Tue May 13 19:30 - 22:14  (02:44)
charlie  pts/2        10.0.0.7         Tue May 13 15:00 - 17:20  (02:20)
reboot   system boot  5.15.0-92-generi Tue May 13 09:00   still running
bob      pts/1        192.168.1.42     Mon May 12 22:30 - 23:45  (01:15)
alice    pts/0        :0               Mon May 12 09:00 - 18:00  (09:00)

wtmp begins Wed Apr 30 03:14:01 2026
""",
        "source_when_real": "real `last -n 10` (Debian container; wtmp is usually empty in fresh containers → fall back)",
        "source_when_captured": "captured from a workstation's wtmp",
    },
    {
        "name": "find",
        "title": "File search with perm-denied clutter",
        # Always use captured — root in the container sees all of /etc,
        # so the perm-denied clutter the normalizer strips wouldn't
        # appear in real output. Captured shows a typical non-root user
        # scenario on a real Linux server.
        "prefer_captured": True,
        "shell_cmd": "find /etc -name *.conf -maxdepth 3 2>&1",
        "captured": """/etc/cloud/cloud.cfg
find: '/etc/ssl/private': Permission denied
/etc/dpkg/dpkg.cfg
/etc/dhcp/dhclient.conf
find: '/etc/sudoers.d': Permission denied
/etc/ldap/ldap.conf
/etc/python3.10/sitecustomize.conf
find: '/etc/credentials.d': Permission denied
/etc/wgetrc
/etc/init.d/cron.conf
find: '/etc/security/credentials': Permission denied
find: '/etc/ssh/ssh_host_rsa_key': Permission denied
find: '/etc/cron.d/private': Permission denied
""",
        "source_when_real": "real `find /etc -name *.conf` as nobody (Debian container)",
        "source_when_captured": "captured from a Linux server, run as non-root",
    },
    {
        "name": "apt-list",
        "title": "APT upgradable packages",
        "setup": "apt-get update >/dev/null 2>&1 || true",
        "shell_cmd": "apt list --upgradable 2>&1",
        "captured": """Listing... Done
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
nginx/jammy 1.18.0-6ubuntu14.4 amd64 [upgradable from: 1.18.0-6ubuntu14.3]
libssl3/jammy-security 3.0.2-0ubuntu1.15 amd64 [upgradable from: 3.0.2-0ubuntu1.14]
linux-image-generic/jammy-updates 5.15.0.92.92 amd64 [upgradable from: 5.15.0.91.91]
libpython3.10/jammy-updates 3.10.12-1~22.04.4 amd64 [upgradable from: 3.10.12-1~22.04.3]
curl/jammy-security 7.81.0-1ubuntu1.16 amd64 [upgradable from: 7.81.0-1ubuntu1.15]
""",
        "source_when_real": "real `apt list --upgradable` (Debian container after `apt update`; usually empty → fall back)",
        "source_when_captured": "captured from an Ubuntu 22.04 server with pending updates",
    },
    {
        "name": "smartctl-health",
        "title": "SMART overall health",
        "shell_cmd": "smartctl -H /dev/sda 2>&1",
        "captured": """smartctl 7.3 2022-02-28 r5338 [x86_64-linux-5.15.0-92-generic] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

""",
        "source_when_real": "real `smartctl -H` (will only differ from the captured PASSED fixture if a real disk is present)",
        "source_when_captured": "captured from smartmontools 7.3 on a healthy SATA disk (no /dev/sda in the container)",
    },
    {
        "name": "smartctl-attrs",
        "title": "SMART attribute table",
        "shell_cmd": "smartctl -A /dev/sda 2>&1",
        "captured": """smartctl 7.3 2022-02-28 r5338 [x86_64-linux-5.15.0-92-generic] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF READ SMART DATA SECTION ===
SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  1 Raw_Read_Error_Rate     0x000f   100   100   006    Pre-fail  Always       -       0
  3 Spin_Up_Time            0x0003   098   098   000    Pre-fail  Always       -       0
  4 Start_Stop_Count        0x0032   100   100   020    Old_age   Always       -       42
  5 Reallocated_Sector_Ct   0x0033   100   100   010    Pre-fail  Always       -       0
  7 Seek_Error_Rate         0x000f   072   060   030    Pre-fail  Always       -       18329234
  9 Power_On_Hours          0x0032   088   088   000    Old_age   Always       -       10523
 12 Power_Cycle_Count       0x0032   100   100   020    Old_age   Always       -       38
192 Power-Off_Retract_Count 0x0032   100   100   000    Old_age   Always       -       21
194 Temperature_Celsius     0x0022   034   047   000    Old_age   Always       -       34 (Min/Max 22/47)
197 Current_Pending_Sector  0x0012   100   100   000    Old_age   Always       -       0
198 Offline_Uncorrectable   0x0010   100   100   000    Old_age   Offline      -       0
199 UDMA_CRC_Error_Count    0x003e   200   200   000    Old_age   Always       -       0

""",
        "source_when_captured": "captured from smartmontools 7.3 on a healthy SATA disk (no /dev/sda in the container)",
    },
    {
        "name": "iptables",
        "title": "Firewall rules",
        "shell_cmd": "iptables -L -n -v 2>&1",
        "captured": """Chain INPUT (policy ACCEPT 142 packets, 16K bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0
   12   720 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    8   512 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80
   42  3.2K DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
   18 1.4K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED

Chain OUTPUT (policy ACCEPT 89 packets, 12K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
   18 1.4K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
""",
        "source_when_captured": "captured from a Linux host (container lacks CAP_NET_ADMIN → iptables refuses)",
    },
    {
        "name": "virsh-list",
        "title": "Libvirt domains",
        "shell_cmd": "virsh list --all 2>&1",
        "captured": """ Id   Name           State
----------------------------------
 1    web-server     running
 2    db-primary     running
 -    backup-host    shut off
 -    test-vm        shut off
""",
        "source_when_captured": "captured from a libvirt host (no libvirtd in the container)",
    },
    {
        "name": "systemctl-status",
        "title": "Service status",
        "shell_cmd": "systemctl status nginx 2>&1",
        "captured": """● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2026-05-14 03:14:01 UTC; 2h 12min ago
       Docs: man:nginx(8)
    Process: 987 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 988 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
   Main PID: 1234 (nginx)
      Tasks: 5 (limit: 4915)
     Memory: 8.4M
     CGroup: /system.slice/nginx.service
             ├─1234 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─1235 nginx: worker process
             ├─1236 nginx: worker process
             ├─1237 nginx: worker process
             └─1238 nginx: worker process

May 14 03:14:01 web-server systemd[1]: Starting A high performance web server...
May 14 03:14:01 web-server systemd[1]: Started A high performance web server.
""",
        "source_when_captured": "captured from a real systemd host (no PID 1 systemd in the container)",
    },
    {
        "name": "systemctl-list-units",
        "title": "Service list",
        # Plain agent invocation — no `| head` (which would trigger
        # pipeline rejection and skip the systemctl-list-units filter).
        "shell_cmd": "systemctl list-units --type=service --no-pager 2>&1",
        "captured": """  UNIT                          LOAD   ACTIVE     SUB     DESCRIPTION
  cron.service                  loaded active     running Regular background program processing daemon
  dbus.service                  loaded active     running D-Bus System Message Bus
  nginx.service                 loaded active     running A high performance web server and a reverse proxy server
  ssh.service                   loaded active     running OpenBSD Secure Shell server
  systemd-journald.service      loaded active     running Journal Service
  systemd-logind.service        loaded active     running Login Service

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

320 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
""",
        "source_when_captured": "captured from a real systemd host",
    },
    {
        "name": "zpool-status",
        "title": "ZFS pool status",
        "shell_cmd": "zpool status 2>&1",
        "captured": """  pool: tank
 state: ONLINE
  scan: scrub repaired 0B in 00:02:34 with 0 errors on Sun May 12 03:14:17 2026
config:

	NAME        STATE     READ WRITE CKSUM
	tank        ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sda     ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	  mirror-1  ONLINE       0     0     0
	    sdc     ONLINE       0     0     0
	    sdd     ONLINE       0     0     0

errors: No known data errors
""",
        "source_when_captured": "captured from a ZFS host (no ZFS kernel module in container)",
    },
    {
        "name": "lsblk",
        "title": "Block devices",
        "shell_cmd": "lsblk 2>&1",
        "captured": None,
        "source_when_real": "real `lsblk` (Debian container; overlay-fs view)",
    },
    {
        "name": "docker-ps",
        "title": "Docker containers",
        "shell_cmd": "docker ps 2>&1",
        "captured": """CONTAINER ID   IMAGE                COMMAND                  CREATED          STATUS         PORTS                                       NAMES
abc123def456   nginx:1.25-alpine    "/docker-entrypoint.…"   2 hours ago      Up 2 hours     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   web-proxy
789012345678   postgres:16-alpine   "docker-entrypoint.s…"   2 days ago       Up 2 days      0.0.0.0:5432->5432/tcp                      db-primary
fedcba987654   redis:7-alpine       "docker-entrypoint.s…"   2 days ago       Up 2 days      0.0.0.0:6379->6379/tcp                      cache
""",
        "source_when_captured": "captured from a real Docker host (no daemon in the container)",
    },
    {
        "name": "dmesg",
        "title": "Kernel ring buffer",
        # Plain `dmesg` — `| head` would skip the dmesg plugin.
        "shell_cmd": "dmesg 2>&1",
        # Long enough (>50 lines, no critical events) to trigger the
        # plugin's head/tail-bias path: keep first 5 + last 30, elide
        # the routine middle.
        "captured": "\n".join([
            "[    0.000000] Linux version 5.15.0-92-generic (Ubuntu 22.04)",
            "[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-92-generic root=UUID=...",
            "[    0.000000] x86/fpu: Supported XSAVE features 0x202e7",
            "[    0.012000] BIOS-provided physical RAM map:",
            "[    0.012000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable",
            "[    0.012000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved",
            "[    0.012000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved",
            "[    0.012000] BIOS-e820: [mem 0x0000000000100000-0x000000007ffeffff] usable",
            "[    0.012000] BIOS-e820: [mem 0x000000007fff0000-0x000000007fffffff] ACPI data",
            "[    0.234567] ACPI: Early table checksum verification disabled",
            "[    0.345678] ACPI: RSDP 0x00000000000F5300 000024 (v02 BOCHS )",
            "[    0.456789] usb 1-1: new high-speed USB device number 2 using ehci-pci",
            "[    0.567890] usb 1-1: New USB device found, idVendor=1d6b, idProduct=0002",
            "[    0.678901] usb 1-1: New USB device strings: Mfr=3, Product=2, SerialNumber=1",
            "[    0.789012] usb 1-2: new high-speed USB device number 3 using ehci-pci",
            "[    0.890123] usb 1-2: New USB device found, idVendor=1d6b, idProduct=0002",
            "[    1.012345] usb 1-3: new high-speed USB device number 4 using ehci-pci",
            "[    1.123456] usb 1-3: New USB device found, idVendor=1d6b, idProduct=0002",
            "[    1.234567] scsi host0: ahci",
            "[    1.345678] scsi host1: ahci",
            "[    1.456789] scsi host2: ahci",
            "[    1.567890] ata1: SATA link up 6.0 Gbps (SStatus 133 SControl 300)",
            "[    1.678901] ata2: SATA link up 6.0 Gbps (SStatus 133 SControl 300)",
            "[    1.789012] ata3: SATA link down (SStatus 0 SControl 300)",
            "[    1.890123] ata1.00: ATA-9: Samsung SSD 970, EXM02B6Q, max UDMA/133",
            "[    2.012345] ata1.00: 1000215216 sectors, multi 16: LBA48 NCQ (depth 32)",
            "[    2.123456] ata1.00: configured for UDMA/133",
            "[    2.234567] sd 0:0:0:0: Attached scsi generic sg0 type 0",
            "[    2.345678] sd 0:0:0:0: [sda] 1000215216 512-byte logical blocks: (512 GB/477 GiB)",
            "[    2.456789] sd 0:0:0:0: [sda] Write Protect is off",
            "[    2.567890] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled",
            "[    2.678901] sda: sda1 sda2 sda3",
            "[    2.789012] sd 0:0:0:0: [sda] Attached SCSI disk",
            "[    3.012345] PM: Image not found (code -22)",
            "[    3.123456] random: crng init done",
            "[    3.234567] systemd[1]: systemd 249.11-0ubuntu3.10 running in system mode",
            "[    3.345678] systemd[1]: Detected virtualization kvm.",
            "[    3.456789] systemd[1]: Set hostname to <web-server>.",
            "[    3.567890] systemd[1]: Created slice Slice /system/getty.",
            "[    3.678901] systemd[1]: Reached target Local File Systems.",
            "[    3.789012] systemd[1]: Reached target Network is Online.",
            "[    3.890123] systemd[1]: Started OpenBSD Secure Shell server.",
            "[    4.012345] systemd[1]: Started nginx.",
            "[   12.345678] EXT4-fs (sda1): mounted filesystem with ordered data mode",
            "[   12.456789] EXT4-fs (sda2): mounted filesystem with ordered data mode",
            "[   12.567890] EXT4-fs (sda3): mounted filesystem with ordered data mode",
            "[   23.456789] e1000e: eth0 NIC Link is Up 1000 Mbps Full Duplex",
            "[   23.567890] IPv6: ADDRCONF(NETDEV_UP): eth0: link becomes ready",
            "[   45.678901] new full-speed USB device number 5 using xhci_hcd",
            "[   45.789012] usb 2-1: New USB device found, idVendor=05ac, idProduct=8243",
            "[  123.456789] hrtimer: interrupt took 4123456 ns",
            "[  234.567890] CPU0: Core temperature/speed normal",
            "[  345.678901] perf: interrupt took too long (2503 > 2500), lowering kernel.perf_event_max_sample_rate",
            "[  456.789012] eth0: link is up at 1000 Mbps",
            "[  567.890123] systemd-journald[412]: Successfully sent stream file descriptor to service manager.",
            "[  678.901234] audit: type=1334 audit(...): prog-id=42 op=LOAD",
            "[  789.012345] audit: type=1334 audit(...): prog-id=43 op=LOAD",
            "[  890.123456] systemd[1]: Started Daily apt download activities.",
            "[ 1000.123456] e1000e: eth0 NIC Link is Down",
            "[ 1000.234567] e1000e: eth0 NIC Link is Up 1000 Mbps Full Duplex",
            "[ 2000.345678] systemd[1]: Started Cleanup of Temporary Directories.",
            "[ 3600.456789] systemd[1]: Started Daily apt download activities.",
        ]),
        "source_when_captured": "captured boot dmesg from a Linux server (60 lines; container lacks /dev/kmsg access)",
    },
    {
        "name": "journalctl",
        "title": "Systemd journal",
        "shell_cmd": "journalctl -u nginx --no-pager -n 30 2>&1",
        "captured": """May 14 03:14:01 web-server systemd[1]: Starting A high performance web server...
May 14 03:14:01 web-server nginx[988]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
May 14 03:14:01 web-server nginx[988]: nginx: configuration file /etc/nginx/nginx.conf test is successful
May 14 03:14:01 web-server systemd[1]: Started A high performance web server.
May 14 03:14:15 web-server nginx[1234]: 127.0.0.1 - - [14/May/2026:03:14:15 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.81.0"
May 14 03:14:22 web-server nginx[1234]: 127.0.0.1 - - [14/May/2026:03:14:22 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.81.0"
May 14 03:14:23 web-server nginx[1234]: 127.0.0.1 - - [14/May/2026:03:14:23 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.81.0"
May 14 03:14:24 web-server nginx[1234]: 127.0.0.1 - - [14/May/2026:03:14:24 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.81.0"
May 14 03:14:25 web-server nginx[1234]: 127.0.0.1 - - [14/May/2026:03:14:25 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.81.0"
May 14 03:14:30 web-server nginx[1234]: 192.168.1.42 - - [14/May/2026:03:14:30 +0000] "POST /api/login HTTP/1.1" 200 89 "-" "Mozilla/5.0"
""",
        "source_when_captured": "captured from a real systemd host",
    },
]


# ---------------------------------------------------------------------
# Two run modes: inside the container (real Linux tools) or on the host.
# Inside the container, $TX_IN_DOCKER=1 (set by the Dockerfile).
# ---------------------------------------------------------------------

def _in_container() -> bool:
    import os
    return os.environ.get("TX_IN_DOCKER") == "1"


def _run_local(shell: str, *, timeout: float = 20) -> str | None:
    """Run a shell snippet locally; return stdout (+ stderr if non-zero exit)."""
    try:
        res = subprocess.run(
            shell, shell=True, capture_output=True, text=True,
            timeout=timeout, executable="/bin/bash",
        )
        return res.stdout + (res.stderr if res.returncode != 0 else "")
    except (subprocess.TimeoutExpired, OSError):
        return None


def _useful(out: str | None, *, min_nonblank_lines: int = 5) -> bool:
    """Heuristic: is this output worth using as the 'raw' sample?

    To *demonstrate* a normalizer we need at least a few lines of
    realistic content. Trivial errors (`Cannot open ...`, `Permission
    denied`, `No such file or directory`, `System has not been booted`,
    a header-only response with no data rows) don't show the normalizer
    doing meaningful work — fall back to a captured Linux-server
    fixture instead.

    Rejection criteria (any → fall back):
    - None
    - `command not found`
    - any of the known "tool installed but environment can't produce
      real output" markers (no PID 1 systemd, no /dev/sda, no daemon,
      etc.)
    - fewer than ``min_nonblank_lines`` non-blank lines
    """
    if out is None:
        return False
    s = out.strip()
    if not s:
        return False
    if "command not found" in out:
        return False
    REJECT_MARKERS = (
        "No such file or directory",
        "Permission denied (you must be root)",
        "Failed to connect to the hypervisor",
        "Cannot connect to the Docker daemon",
        "System has not been booted with systemd",
        "Failed to read messages from /dev/kmsg",
        "Operation not permitted",
        "No journal files were found",
        "modprobe: FATAL",
        "ZFS modules are not loaded",
        "no pools available",
        "Smartctl open device",
        "Unable to detect device type",
        "/dev/sda: failed to open",
        "/dev/sda: No such",
        "Cannot stat device",
    )
    for m in REJECT_MARKERS:
        if m in out and len(out) < 800:
            return False
    nonblank = sum(1 for l in out.splitlines() if l.strip())
    return nonblank >= min_nonblank_lines


def _resolve(fx: dict) -> tuple[str, str, str]:
    """Return (raw_text, source_label, mode) for this fixture.

    mode is 'real' or 'captured'.

    A fixture may set ``prefer_captured = True`` when the container's
    real output won't demonstrate the normalizer (e.g. `find` as root
    has no perm-denied lines to strip; `apt list --upgradable` on a
    fresh image is empty). Those still ship with a clean captured
    fixture sourced from a real Linux server.
    """
    real = None
    if _in_container() and not fx.get("prefer_captured"):
        if fx.get("setup"):
            _run_local(fx["setup"], timeout=15)
            time.sleep(0.1)
        real = _run_local(fx["shell_cmd"], timeout=20)
    if _useful(real):
        return (real, fx.get("source_when_real",
                              "real (Linux container)"), "real")
    captured = fx.get("captured")
    if captured:
        return (captured, fx.get("source_when_captured",
                                 "captured Linux output"), "captured")
    return (
        f"(no output: container produced nothing useful for `{fx['shell_cmd']}` "
        f"and no captured fixture was set)",
        "no-output",
        "captured",
    )


# ---------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------

def fence(text: str) -> str:
    return f"```\n{text.rstrip()}\n```"


def render() -> str:
    out: list[str] = []
    out.append("# `tx` Compaction Samples")
    out.append("")
    out.append("Auto-generated by `scripts/generate_compaction_samples.py`.")
    out.append("Before/after pairs for every builtin normalizer in `tx_compact/`.")
    out.append("")
    if _in_container():
        out.append("**Generated inside the tx-tests Docker container** "
                   "(Debian bookworm). Most samples are real `tx run` output "
                   "captured against the installed Linux binaries; the rest "
                   "are captured fixtures from Linux servers where the "
                   "container can't run the tool (no PID 1 systemd, no ZFS "
                   "kernel module, no libvirtd, etc.). Source is labelled "
                   "per section.")
    else:
        out.append("**Generated on the host (NOT in the Docker container).** "
                   "This means `_run_local()` ran each command on the dev "
                   "machine (likely macOS). Most rows will fall back to "
                   "captured fixtures. To regenerate from real Linux output, "
                   "run: `make samples` or directly: "
                   "`docker run --rm -v $PWD:/work --entrypoint "
                   "/work/scripts/generate_compaction_samples.py "
                   "tx-tests:latest > docs/compaction_samples.md`")
    out.append("")
    out.append("Each section shows:")
    out.append("- The shell command an agent would issue.")
    out.append("- **Raw** — what `tx run --raw <pane> '<cmd>'` returns "
               "(cleaned bytes verbatim).")
    out.append("- **Compacted** — what `tx run --terse <pane> '<cmd>'` returns.")
    out.append("- Byte-savings + which compaction layers fired.")
    out.append("")
    out.append("**If a normalizer dropped information you need**, re-run "
               "the single command with `--no-normalize` (keep L1-L5) or "
               "`--raw` (escape hatch). See `docs/tx-doc-compaction.md` "
               "→ \"When compaction strips info you need\".")
    out.append("")

    total_in = 0
    total_out = 0
    rows: list[tuple[str, int, int, float, str, str, str]] = []

    for fx in FIXTURES:
        raw, source, mode = _resolve(fx)
        ctx = CompactCtx(
            mode="terse",
            cmd=fx["shell_cmd"],
            pane="p1",
            run_id="r-sample",
            token_budget=None,
        )
        result = compact(raw, ctx)
        out.append(f"## {fx['title']} — `{fx['name']}` ({mode})")
        out.append("")
        out.append(f"**Source:** {source}")
        out.append("")
        out.append(f"**Command:** `{fx['shell_cmd']}`")
        out.append("")
        out.append(f"**Raw ({len(raw):,} bytes):**")
        out.append("")
        out.append(fence(raw))
        out.append("")
        out.append(f"**Compacted ({len(result.text):,} bytes, "
                   f"saved {result.saved_pct:.1f}%, "
                   f"tier={result.tier.name.lower()}):**")
        out.append("")
        out.append(fence(result.text))
        out.append("")
        layers = ", ".join(result.applied_layers) if result.applied_layers else "(none)"
        out.append(f"**Layers fired:** {layers}")
        out.append("")
        if result.notes:
            out.append("**Notes:**")
            out.append("")
            for note in result.notes:
                out.append(f"- {note}")
            out.append("")
        out.append("---")
        out.append("")

        total_in += len(raw)
        total_out += len(result.text)
        rows.append((fx["name"], len(raw), len(result.text), result.saved_pct,
                     layers, result.tier.name.lower(), mode))

    # Headline summary table inserted after the intro.
    summary: list[str] = []
    summary.append("## Headline savings")
    summary.append("")
    overall = (100.0 * (total_in - total_out) / total_in) if total_in else 0.0
    summary.append(f"Across the {len(rows)} normalizers below: "
                   f"**{total_in:,} bytes → {total_out:,} bytes "
                   f"({overall:.1f}% saved)**.")
    summary.append("")
    summary.append("| Normalizer | Source | Raw B | Compacted B | Saved | Tier | Layers |")
    summary.append("|---|---|---:|---:|---:|---|---|")
    for name, ib, ob, pct, layers, tier, mode in rows:
        summary.append(f"| `{name}` | {mode} | {ib:,} | {ob:,} | "
                       f"{pct:.1f}% | {tier} | {layers} |")
    summary.append("")
    summary.append("`source` = `real` (ran inside the Docker container, "
                   "Debian + the sysadmin toolbox) or `captured` "
                   "(snapshot from a Linux server where the unprivileged "
                   "container can't run the tool).")
    summary.append("")
    summary.append("---")
    summary.append("")
    # Insert summary right after the intro paragraphs (before any section).
    insert_at = next(i for i, line in enumerate(out) if line.startswith("## "))
    return "\n".join(out[:insert_at] + summary + out[insert_at:])


# ---------------------------------------------------------------------
# Self-relaunch into Docker if not already inside
# ---------------------------------------------------------------------

def _docker_available() -> bool:
    return shutil.which("docker") is not None


def _relaunch_in_container(image: str, rebuild: bool) -> int:
    """Build (if needed) the test image and re-run this script inside.
    Streams the rendered markdown back to stdout."""
    if rebuild:
        print(f"[samples] docker build --no-cache -t {image} ...",
              file=sys.stderr)
        rc = subprocess.call(
            ["docker", "build", "--no-cache", "-t", image, str(REPO)],
        )
        if rc != 0:
            return rc
    else:
        # Always do a (cached) build to pick up code changes.
        print(f"[samples] docker build -t {image} ...", file=sys.stderr)
        rc = subprocess.call(["docker", "build", "-t", image, str(REPO)])
        if rc != 0:
            return rc

    print(f"[samples] docker run inside {image} ...", file=sys.stderr)
    proc = subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{REPO}:/work",
            "--entrypoint", "/work/scripts/generate_compaction_samples.py",
            image,
        ],
        capture_output=True, text=True,
    )
    # Forward stderr (informational) and emit stdout (the markdown).
    sys.stderr.write(proc.stderr)
    sys.stdout.write(proc.stdout)
    return proc.returncode


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", default="tx-tests:latest")
    parser.add_argument("--rebuild", action="store_true")
    parser.add_argument("--host", action="store_true",
                        help="Skip the docker relaunch and render from the host "
                             "(samples will mostly fall back to captured fixtures).")
    args = parser.parse_args()

    if _in_container() or args.host:
        sys.stdout.write(render())
        return 0
    if not _docker_available():
        print("[samples] docker not available; rendering on host (most "
              "samples will be captured fixtures). Pass --host to silence.",
              file=sys.stderr)
        sys.stdout.write(render())
        return 0
    return _relaunch_in_container(args.image, args.rebuild)


if __name__ == "__main__":
    sys.exit(main())
